namespace Nace;

internal static class NaceData
{
    internal static readonly (string Code, string Description, string Section, string SectionName)[] Classes =
    [
        ("01.11", "Growing of cereals, other than rice, leguminous crops and oil seeds", "A", "Agriculture, Forestry and Fishing"),
        ("01.12", "Growing of rice", "A", "Agriculture, Forestry and Fishing"),
        ("01.13", "Growing of vegetables and melons, roots and tubers", "A", "Agriculture, Forestry and Fishing"),
        ("01.14", "Growing of sugar cane", "A", "Agriculture, Forestry and Fishing"),
        ("01.15", "Growing of tobacco", "A", "Agriculture, Forestry and Fishing"),
        ("01.16", "Growing of fibre crops", "A", "Agriculture, Forestry and Fishing"),
        ("01.19", "Growing of other non-perennial crops", "A", "Agriculture, Forestry and Fishing"),
        ("01.21", "Growing of grapes", "A", "Agriculture, Forestry and Fishing"),
        ("01.22", "Growing of tropical and subtropical fruits", "A", "Agriculture, Forestry and Fishing"),
        ("01.23", "Growing of citrus fruits", "A", "Agriculture, Forestry and Fishing"),
        ("01.24", "Growing of pome fruits and stone fruits", "A", "Agriculture, Forestry and Fishing"),
        ("01.25", "Growing of other tree and bush fruits and nuts", "A", "Agriculture, Forestry and Fishing"),
        ("01.26", "Growing of oleaginous fruits", "A", "Agriculture, Forestry and Fishing"),
        ("01.27", "Growing of beverage crops", "A", "Agriculture, Forestry and Fishing"),
        ("01.28", "Growing of spices, aromatic, drug and pharmaceutical crops", "A", "Agriculture, Forestry and Fishing"),
        ("01.29", "Growing of other perennial crops", "A", "Agriculture, Forestry and Fishing"),
        ("01.30", "Plant propagation", "A", "Agriculture, Forestry and Fishing"),
        ("01.41", "Raising of dairy cattle", "A", "Agriculture, Forestry and Fishing"),
        ("01.42", "Raising of other cattle and buffaloes", "A", "Agriculture, Forestry and Fishing"),
        ("01.43", "Raising of horses and other equines", "A", "Agriculture, Forestry and Fishing"),
        ("01.44", "Raising of camels and camelids", "A", "Agriculture, Forestry and Fishing"),
        ("01.45", "Raising of sheep and goats", "A", "Agriculture, Forestry and Fishing"),
        ("01.46", "Raising of swine and pigs", "A", "Agriculture, Forestry and Fishing"),
        ("01.47", "Raising of poultry", "A", "Agriculture, Forestry and Fishing"),
        ("01.48", "Raising of other animals", "A", "Agriculture, Forestry and Fishing"),
        ("01.50", "Mixed farming", "A", "Agriculture, Forestry and Fishing"),
        ("01.61", "Support activities for crop production", "A", "Agriculture, Forestry and Fishing"),
        ("01.62", "Support activities for animal production", "A", "Agriculture, Forestry and Fishing"),
        ("01.63", "Post-harvest crop activities and seed processing for propagation", "A", "Agriculture, Forestry and Fishing"),
        ("01.70", "Hunting, trapping and related service activities", "A", "Agriculture, Forestry and Fishing"),
        ("02.10", "Silviculture and other forestry activities", "A", "Agriculture, Forestry and Fishing"),
        ("02.20", "Logging", "A", "Agriculture, Forestry and Fishing"),
        ("02.30", "Gathering of wild growing non-wood products", "A", "Agriculture, Forestry and Fishing"),
        ("02.40", "Support services to forestry", "A", "Agriculture, Forestry and Fishing"),
        ("03.11", "Marine fishing", "A", "Agriculture, Forestry and Fishing"),
        ("03.12", "Freshwater fishing", "A", "Agriculture, Forestry and Fishing"),
        ("03.21", "Marine aquaculture", "A", "Agriculture, Forestry and Fishing"),
        ("03.22", "Freshwater aquaculture", "A", "Agriculture, Forestry and Fishing"),
        ("03.30", "Support activities for fishing and aquaculture", "A", "Agriculture, Forestry and Fishing"),
        ("05.10", "Mining of hard coal", "B", "Mining and Quarrying"),
        ("05.20", "Mining of lignite", "B", "Mining and Quarrying"),
        ("06.10", "Extraction of crude petroleum", "B", "Mining and Quarrying"),
        ("06.20", "Extraction of natural gas", "B", "Mining and Quarrying"),
        ("07.10", "Mining of iron ores", "B", "Mining and Quarrying"),
        ("07.21", "Mining of uranium and thorium ores", "B", "Mining and Quarrying"),
        ("07.29", "Mining of other non-ferrous metal ores", "B", "Mining and Quarrying"),
        ("08.11", "Quarrying of ornamental stone, limestone, gypsum, slate and other stone", "B", "Mining and Quarrying"),
        ("08.12", "Operation of gravel and sand pits and mining of clay and kaolin", "B", "Mining and Quarrying"),
        ("08.91", "Mining of chemical and fertiliser minerals", "B", "Mining and Quarrying"),
        ("08.92", "Extraction of peat", "B", "Mining and Quarrying"),
        ("08.93", "Extraction of salt", "B", "Mining and Quarrying"),
        ("08.99", "Other mining and quarrying n.e.c.", "B", "Mining and Quarrying"),
        ("09.10", "Support activities for petroleum and natural gas extraction", "B", "Mining and Quarrying"),
        ("09.90", "Support activities for other mining and quarrying", "B", "Mining and Quarrying"),
        ("10.11", "Processing and preserving of meat, except of poultry meat", "C", "Manufacturing"),
        ("10.12", "Processing and preserving of poultry meat", "C", "Manufacturing"),
        ("10.13", "Production of meat and poultry meat products", "C", "Manufacturing"),
        ("10.20", "Processing and preserving of fish, crustaceans and molluscs", "C", "Manufacturing"),
        ("10.31", "Processing and preserving of potatoes", "C", "Manufacturing"),
        ("10.32", "Manufacture of fruit and vegetable juice", "C", "Manufacturing"),
        ("10.39", "Other processing and preserving of fruit and vegetables", "C", "Manufacturing"),
        ("10.41", "Manufacture of oils and fats", "C", "Manufacturing"),
        ("10.42", "Manufacture of margarine and similar edible fats", "C", "Manufacturing"),
        ("10.51", "Manufacture of dairy products", "C", "Manufacturing"),
        ("10.52", "Manufacture of ice cream and other edible ice", "C", "Manufacturing"),
        ("10.61", "Manufacture of grain mill products", "C", "Manufacturing"),
        ("10.62", "Manufacture of starches and starch products", "C", "Manufacturing"),
        ("10.71", "Manufacture of bread; manufacture of fresh pastry goods and cakes", "C", "Manufacturing"),
        ("10.72", "Manufacture of rusks, biscuits, preserved pastries and cakes", "C", "Manufacturing"),
        ("10.73", "Manufacture of farinaceous products", "C", "Manufacturing"),
        ("10.81", "Manufacture of sugar", "C", "Manufacturing"),
        ("10.82", "Manufacture of cocoa, chocolate and sugar confectionery", "C", "Manufacturing"),
        ("10.83", "Processing of tea and coffee", "C", "Manufacturing"),
        ("10.84", "Manufacture of condiments and seasonings", "C", "Manufacturing"),
        ("10.85", "Manufacture of prepared meals and dishes", "C", "Manufacturing"),
        ("10.86", "Manufacture of homogenised food preparations and dietetic food", "C", "Manufacturing"),
        ("10.89", "Manufacture of other food products n.e.c.", "C", "Manufacturing"),
        ("10.91", "Manufacture of prepared feeds for farm animals", "C", "Manufacturing"),
        ("10.92", "Manufacture of prepared pet foods", "C", "Manufacturing"),
        ("11.01", "Distilling, rectifying and blending of spirits", "C", "Manufacturing"),
        ("11.02", "Manufacture of wine from grape", "C", "Manufacturing"),
        ("11.03", "Manufacture of cider and other fermented fruit beverages", "C", "Manufacturing"),
        ("11.04", "Manufacture of other non-distilled fermented beverages", "C", "Manufacturing"),
        ("11.05", "Manufacture of beer", "C", "Manufacturing"),
        ("11.06", "Manufacture of malt", "C", "Manufacturing"),
        ("11.07", "Manufacture of soft drinks and bottled waters", "C", "Manufacturing"),
        ("12.00", "Manufacture of tobacco products", "C", "Manufacturing"),
        ("13.10", "Preparation and spinning of textile fibres", "C", "Manufacturing"),
        ("13.20", "Weaving of textiles", "C", "Manufacturing"),
        ("13.30", "Finishing of textiles", "C", "Manufacturing"),
        ("13.91", "Manufacture of knitted and crocheted fabrics", "C", "Manufacturing"),
        ("13.92", "Manufacture of household textiles and made-up furnishing articles", "C", "Manufacturing"),
        ("13.93", "Manufacture of carpets and rugs", "C", "Manufacturing"),
        ("13.94", "Manufacture of cordage, rope, twine and netting", "C", "Manufacturing"),
        ("13.95", "Manufacture of non-wovens and non-woven articles", "C", "Manufacturing"),
        ("13.96", "Manufacture of other technical and industrial textiles", "C", "Manufacturing"),
        ("13.99", "Manufacture of other textiles n.e.c.", "C", "Manufacturing"),
        ("14.10", "Manufacture of knitted and crocheted apparel", "C", "Manufacturing"),
        ("14.21", "Manufacture of outerwear", "C", "Manufacturing"),
        ("14.22", "Manufacture of underwear", "C", "Manufacturing"),
        ("14.23", "Manufacture of workwear", "C", "Manufacturing"),
        ("14.24", "Manufacture of leather clothes and fur apparel", "C", "Manufacturing"),
        ("14.29", "Manufacture of other wearing apparel and accessories n.e.c.", "C", "Manufacturing"),
        ("15.11", "Tanning, dressing, dyeing of leather and fur", "C", "Manufacturing"),
        ("15.12", "Manufacture of luggage, handbags, saddlery and harness of any material", "C", "Manufacturing"),
        ("15.20", "Manufacture of footwear", "C", "Manufacturing"),
        ("16.11", "Sawmilling and planing of wood", "C", "Manufacturing"),
        ("16.12", "Processing and finishing of wood", "C", "Manufacturing"),
        ("16.21", "Manufacture of veneer sheets and wood-based panels", "C", "Manufacturing"),
        ("16.22", "Manufacture of assembled parquet floors", "C", "Manufacturing"),
        ("16.23", "Manufacture of other builders’ carpentry and joinery", "C", "Manufacturing"),
        ("16.24", "Manufacture of wooden containers", "C", "Manufacturing"),
        ("16.25", "Manufacture of doors and windows of wood", "C", "Manufacturing"),
        ("16.26", "Manufacture of solid fuels from vegetable biomass", "C", "Manufacturing"),
        ("16.27", "Finishing of wooden products", "C", "Manufacturing"),
        ("16.28", "Manufacture of other products of wood and articles of cork, straw and plaiting materials", "C", "Manufacturing"),
        ("17.11", "Manufacture of pulp", "C", "Manufacturing"),
        ("17.12", "Manufacture of paper and paperboard", "C", "Manufacturing"),
        ("17.21", "Manufacture of corrugated paper, paperboard and containers of paper and paperboard", "C", "Manufacturing"),
        ("17.22", "Manufacture of household and sanitary goods and of toilet requisites", "C", "Manufacturing"),
        ("17.23", "Manufacture of paper stationery", "C", "Manufacturing"),
        ("17.24", "Manufacture of wallpaper", "C", "Manufacturing"),
        ("17.25", "Manufacture of other articles of paper and paperboard", "C", "Manufacturing"),
        ("18.11", "Printing of newspapers", "C", "Manufacturing"),
        ("18.12", "Other printing", "C", "Manufacturing"),
        ("18.13", "Pre-press and pre-media services", "C", "Manufacturing"),
        ("18.14", "Binding and related services", "C", "Manufacturing"),
        ("18.20", "Reproduction of recorded media", "C", "Manufacturing"),
        ("19.10", "Manufacture of coke oven products", "C", "Manufacturing"),
        ("19.20", "Manufacture of refined petroleum products and fossil fuel products", "C", "Manufacturing"),
        ("20.11", "Manufacture of industrial gases", "C", "Manufacturing"),
        ("20.12", "Manufacture of dyes and pigments", "C", "Manufacturing"),
        ("20.13", "Manufacture of other inorganic basic chemicals", "C", "Manufacturing"),
        ("20.14", "Manufacture of other organic basic chemicals", "C", "Manufacturing"),
        ("20.15", "Manufacture of fertilisers and nitrogen compounds", "C", "Manufacturing"),
        ("20.16", "Manufacture of plastics in primary forms", "C", "Manufacturing"),
        ("20.17", "Manufacture of synthetic rubber in primary forms", "C", "Manufacturing"),
        ("20.20", "Manufacture of pesticides, disinfectants and other agrochemical products", "C", "Manufacturing"),
        ("20.30", "Manufacture of paints, varnishes and similar coatings, printing ink and mastics", "C", "Manufacturing"),
        ("20.41", "Manufacture of soap and detergents, cleaning and polishing preparations", "C", "Manufacturing"),
        ("20.42", "Manufacture of perfume and toilet preparations", "C", "Manufacturing"),
        ("20.51", "Manufacture of liquid biofuels", "C", "Manufacturing"),
        ("20.59", "Manufacture of other chemical products n.e.c.", "C", "Manufacturing"),
        ("20.60", "Manufacture of man-made fibres", "C", "Manufacturing"),
        ("21.10", "Manufacture of basic pharmaceutical products", "C", "Manufacturing"),
        ("21.20", "Manufacture of pharmaceutical preparations", "C", "Manufacturing"),
        ("22.11", "Manufacture, retreading and rebuilding of rubber tyres and manufacture of tubes", "C", "Manufacturing"),
        ("22.12", "Manufacture of other rubber products", "C", "Manufacturing"),
        ("22.21", "Manufacture of plastic plates, sheets, tubes and profiles", "C", "Manufacturing"),
        ("22.22", "Manufacture of plastic packing goods", "C", "Manufacturing"),
        ("22.23", "Manufacture of doors and windows of plastic", "C", "Manufacturing"),
        ("22.24", "Manufacture of builders’ ware of plastic", "C", "Manufacturing"),
        ("22.25", "Processing and finishing of plastic products", "C", "Manufacturing"),
        ("22.26", "Manufacture of other plastic products", "C", "Manufacturing"),
        ("23.11", "Manufacture of flat glass", "C", "Manufacturing"),
        ("23.12", "Shaping and processing of flat glass", "C", "Manufacturing"),
        ("23.13", "Manufacture of hollow glass", "C", "Manufacturing"),
        ("23.14", "Manufacture of glass fibres", "C", "Manufacturing"),
        ("23.15", "Manufacture and processing of other glass, including technical glassware", "C", "Manufacturing"),
        ("23.20", "Manufacture of refractory products", "C", "Manufacturing"),
        ("23.31", "Manufacture of ceramic tiles and flags", "C", "Manufacturing"),
        ("23.32", "Manufacture of bricks, tiles and construction products, in baked clay", "C", "Manufacturing"),
        ("23.41", "Manufacture of ceramic household and ornamental articles", "C", "Manufacturing"),
        ("23.42", "Manufacture of ceramic sanitary fixtures", "C", "Manufacturing"),
        ("23.43", "Manufacture of ceramic insulators and insulating fittings", "C", "Manufacturing"),
        ("23.44", "Manufacture of other technical ceramic products", "C", "Manufacturing"),
        ("23.45", "Manufacture of other ceramic products", "C", "Manufacturing"),
        ("23.51", "Manufacture of cement", "C", "Manufacturing"),
        ("23.52", "Manufacture of lime and plaster", "C", "Manufacturing"),
        ("23.61", "Manufacture of concrete products for construction purposes", "C", "Manufacturing"),
        ("23.62", "Manufacture of plaster products for construction purposes", "C", "Manufacturing"),
        ("23.63", "Manufacture of ready-mixed concrete", "C", "Manufacturing"),
        ("23.64", "Manufacture of mortars", "C", "Manufacturing"),
        ("23.65", "Manufacture of fibre cement", "C", "Manufacturing"),
        ("23.66", "Manufacture of other articles of concrete, cement and plaster", "C", "Manufacturing"),
        ("23.70", "Cutting, shaping and finishing of stone", "C", "Manufacturing"),
        ("23.91", "Manufacture of abrasive products", "C", "Manufacturing"),
        ("23.99", "Manufacture of other non-metallic mineral products n.e.c.", "C", "Manufacturing"),
        ("24.10", "Manufacture of basic iron and steel and of ferro-alloys", "C", "Manufacturing"),
        ("24.20", "Manufacture of tubes, pipes, hollow profiles and related fittings, of steel", "C", "Manufacturing"),
        ("24.31", "Cold drawing of bars", "C", "Manufacturing"),
        ("24.32", "Cold rolling of narrow strip", "C", "Manufacturing"),
        ("24.33", "Cold forming or folding", "C", "Manufacturing"),
        ("24.34", "Cold drawing of wire", "C", "Manufacturing"),
        ("24.41", "Precious metals production", "C", "Manufacturing"),
        ("24.42", "Aluminium production", "C", "Manufacturing"),
        ("24.43", "Lead, zinc and tin production", "C", "Manufacturing"),
        ("24.44", "Copper production", "C", "Manufacturing"),
        ("24.45", "Other non-ferrous metal production", "C", "Manufacturing"),
        ("24.46", "Processing of nuclear fuel", "C", "Manufacturing"),
        ("24.51", "Casting of iron", "C", "Manufacturing"),
        ("24.52", "Casting of steel", "C", "Manufacturing"),
        ("24.53", "Casting of light metals", "C", "Manufacturing"),
        ("24.54", "Casting of other non-ferrous metals", "C", "Manufacturing"),
        ("25.11", "Manufacture of metal structures and parts of structures", "C", "Manufacturing"),
        ("25.12", "Manufacture of doors and windows of metal", "C", "Manufacturing"),
        ("25.21", "Manufacture of central heating radiators, steam generators and boilers", "C", "Manufacturing"),
        ("25.22", "Manufacture of other tanks, reservoirs and containers of metal", "C", "Manufacturing"),
        ("25.30", "Manufacture of weapons and ammunition", "C", "Manufacturing"),
        ("25.40", "Forging and shaping metal and powder metallurgy", "C", "Manufacturing"),
        ("25.51", "Coating of metals", "C", "Manufacturing"),
        ("25.52", "Heat treatment of metals", "C", "Manufacturing"),
        ("25.53", "Machining of metals", "C", "Manufacturing"),
        ("25.61", "Manufacture of cutlery", "C", "Manufacturing"),
        ("25.62", "Manufacture of locks and hinges", "C", "Manufacturing"),
        ("25.63", "Manufacture of tools", "C", "Manufacturing"),
        ("25.91", "Manufacture of steel drums and similar containers", "C", "Manufacturing"),
        ("25.92", "Manufacture of light metal packaging", "C", "Manufacturing"),
        ("25.93", "Manufacture of wire products, chain and springs", "C", "Manufacturing"),
        ("25.94", "Manufacture of fasteners and screw machine products", "C", "Manufacturing"),
        ("25.99", "Manufacture of other fabricated metal products n.e.c.", "C", "Manufacturing"),
        ("26.11", "Manufacture of electronic components", "C", "Manufacturing"),
        ("26.12", "Manufacture of loaded electronic boards", "C", "Manufacturing"),
        ("26.20", "Manufacture of computers and peripheral equipment", "C", "Manufacturing"),
        ("26.30", "Manufacture of communication equipment", "C", "Manufacturing"),
        ("26.40", "Manufacture of consumer electronics", "C", "Manufacturing"),
        ("26.51", "Manufacture of instruments and appliances for measuring, testing and navigation", "C", "Manufacturing"),
        ("26.52", "Manufacture of watches and clocks", "C", "Manufacturing"),
        ("26.60", "Manufacture of irradiation, electromedical and electrotherapeutic equipment", "C", "Manufacturing"),
        ("26.70", "Manufacture of optical instruments, magnetic and optical media and photographic equipment", "C", "Manufacturing"),
        ("27.11", "Manufacture of electric motors, generators and transformers", "C", "Manufacturing"),
        ("27.12", "Manufacture of electricity distribution and control apparatus", "C", "Manufacturing"),
        ("27.20", "Manufacture of batteries and accumulators", "C", "Manufacturing"),
        ("27.31", "Manufacture of fibre optic cables", "C", "Manufacturing"),
        ("27.32", "Manufacture of other electronic and electric wires and cables", "C", "Manufacturing"),
        ("27.33", "Manufacture of wiring devices", "C", "Manufacturing"),
        ("27.40", "Manufacture of lighting equipment", "C", "Manufacturing"),
        ("27.51", "Manufacture of electric domestic appliances", "C", "Manufacturing"),
        ("27.52", "Manufacture of non-electric domestic appliances", "C", "Manufacturing"),
        ("27.90", "Manufacture of other electrical equipment", "C", "Manufacturing"),
        ("28.11", "Manufacture of engines and turbines, except aircraft, vehicle and cycle engines", "C", "Manufacturing"),
        ("28.12", "Manufacture of fluid power equipment", "C", "Manufacturing"),
        ("28.13", "Manufacture of other pumps and compressors", "C", "Manufacturing"),
        ("28.14", "Manufacture of other taps and valves", "C", "Manufacturing"),
        ("28.15", "Manufacture of bearings, gears, gearing and driving elements", "C", "Manufacturing"),
        ("28.21", "Manufacture of ovens, furnaces and permanent household heating equipment", "C", "Manufacturing"),
        ("28.22", "Manufacture of lifting and handling equipment", "C", "Manufacturing"),
        ("28.23", "Manufacture of office machinery and equipment, except computers and peripheral equipment", "C", "Manufacturing"),
        ("28.24", "Manufacture of power-driven hand tools", "C", "Manufacturing"),
        ("28.25", "Manufacture of non-domestic air conditioning equipment", "C", "Manufacturing"),
        ("28.29", "Manufacture of other general-purpose machinery n.e.c.", "C", "Manufacturing"),
        ("28.30", "Manufacture of agricultural and forestry machinery", "C", "Manufacturing"),
        ("28.41", "Manufacture of metal forming machinery and machine tools for metal work", "C", "Manufacturing"),
        ("28.42", "Manufacture of other machine tools", "C", "Manufacturing"),
        ("28.91", "Manufacture of machinery for metallurgy", "C", "Manufacturing"),
        ("28.92", "Manufacture of machinery for mining, quarrying and construction", "C", "Manufacturing"),
        ("28.93", "Manufacture of machinery for food, beverage and tobacco processing", "C", "Manufacturing"),
        ("28.94", "Manufacture of machinery for textile, apparel and leather production", "C", "Manufacturing"),
        ("28.95", "Manufacture of machinery for paper and paperboard production", "C", "Manufacturing"),
        ("28.96", "Manufacture of plastics and rubber machinery", "C", "Manufacturing"),
        ("28.97", "Manufacture of additive manufacturing machinery", "C", "Manufacturing"),
        ("28.99", "Manufacture of other special-purpose machinery n.e.c.", "C", "Manufacturing"),
        ("29.10", "Manufacture of motor vehicles", "C", "Manufacturing"),
        ("29.20", "Manufacture of bodies and coachwork for motor vehicles; manufacture of trailers and semi-", "C", "Manufacturing"),
        ("29.31", "Manufacture of electrical and electronic equipment for motor vehicles", "C", "Manufacturing"),
        ("29.32", "Manufacture of other parts and accessories for motor vehicles", "C", "Manufacturing"),
        ("30.11", "Building of civilian ships and floating structures", "C", "Manufacturing"),
        ("30.12", "Building of pleasure and sporting boats", "C", "Manufacturing"),
        ("30.13", "Building of military ships and vessels", "C", "Manufacturing"),
        ("30.20", "Manufacture of railway locomotives and rolling stock", "C", "Manufacturing"),
        ("30.31", "Manufacture of civilian air and spacecraft and related machinery", "C", "Manufacturing"),
        ("30.32", "Manufacture of military air and spacecraft and related machinery", "C", "Manufacturing"),
        ("30.40", "Manufacture of military fighting vehicles", "C", "Manufacturing"),
        ("30.91", "Manufacture of motorcycles", "C", "Manufacturing"),
        ("30.92", "Manufacture of bicycles and invalid carriages", "C", "Manufacturing"),
        ("30.99", "Manufacture of other transport equipment n.e.c.", "C", "Manufacturing"),
        ("31.00", "Manufacture of furniture", "C", "Manufacturing"),
        ("32.11", "Striking of coins", "C", "Manufacturing"),
        ("32.12", "Manufacture of jewellery and related articles", "C", "Manufacturing"),
        ("32.13", "Manufacture of imitation jewellery and related articles", "C", "Manufacturing"),
        ("32.20", "Manufacture of musical instruments", "C", "Manufacturing"),
        ("32.30", "Manufacture of sports goods", "C", "Manufacturing"),
        ("32.40", "Manufacture of games and toys", "C", "Manufacturing"),
        ("32.50", "Manufacture of medical and dental instruments and supplies", "C", "Manufacturing"),
        ("32.91", "Manufacture of brooms and brushes", "C", "Manufacturing"),
        ("32.99", "Other manufacturing n.e.c.", "C", "Manufacturing"),
        ("33.11", "Repair and maintenance of fabricated metal products", "C", "Manufacturing"),
        ("33.12", "Repair and maintenance of machinery", "C", "Manufacturing"),
        ("33.13", "Repair and maintenance of electronic and optical equipment", "C", "Manufacturing"),
        ("33.14", "Repair and maintenance of electrical equipment", "C", "Manufacturing"),
        ("33.15", "Repair and maintenance of civilian ships and boats", "C", "Manufacturing"),
        ("33.16", "Repair and maintenance of civilian air and spacecraft", "C", "Manufacturing"),
        ("33.17", "Repair and maintenance of other civilian transport equipment", "C", "Manufacturing"),
        ("33.18", "Repair and maintenance of military fighting vehicles, ships, boats, air and spacecraft", "C", "Manufacturing"),
        ("33.19", "Repair and maintenance of other equipment", "C", "Manufacturing"),
        ("33.20", "Installation of industrial machinery and equipment", "C", "Manufacturing"),
        ("35.11", "Production of electricity from non-renewable sources", "D", "Electricity, Gas, Steam and Air Conditioning Supply"),
        ("35.12", "Production of electricity from renewable sources", "D", "Electricity, Gas, Steam and Air Conditioning Supply"),
        ("35.13", "Transmission of electricity", "D", "Electricity, Gas, Steam and Air Conditioning Supply"),
        ("35.14", "Distribution of electricity", "D", "Electricity, Gas, Steam and Air Conditioning Supply"),
        ("35.15", "Trade of electricity", "D", "Electricity, Gas, Steam and Air Conditioning Supply"),
        ("35.16", "Storage of electricity", "D", "Electricity, Gas, Steam and Air Conditioning Supply"),
        ("35.21", "Manufacture of gas", "D", "Electricity, Gas, Steam and Air Conditioning Supply"),
        ("35.22", "Distribution of gaseous fuels through mains", "D", "Electricity, Gas, Steam and Air Conditioning Supply"),
        ("35.23", "Trade of gas through mains", "D", "Electricity, Gas, Steam and Air Conditioning Supply"),
        ("35.24", "Storage of gas as part of network supply services", "D", "Electricity, Gas, Steam and Air Conditioning Supply"),
        ("35.30", "Steam and air conditioning supply", "D", "Electricity, Gas, Steam and Air Conditioning Supply"),
        ("35.40", "Activities of brokers and agents for electric power and natural gas", "D", "Electricity, Gas, Steam and Air Conditioning Supply"),
        ("36.00", "Water collection, treatment and supply", "E", "Water Supply, Sewerage, Waste Management and Remediation"),
        ("37.00", "Sewerage", "E", "Water Supply, Sewerage, Waste Management and Remediation"),
        ("38.11", "Collection of non-hazardous waste", "E", "Water Supply, Sewerage, Waste Management and Remediation"),
        ("38.12", "Collection of hazardous waste", "E", "Water Supply, Sewerage, Waste Management and Remediation"),
        ("38.21", "Materials recovery", "E", "Water Supply, Sewerage, Waste Management and Remediation"),
        ("38.22", "Energy recovery", "E", "Water Supply, Sewerage, Waste Management and Remediation"),
        ("38.23", "Other waste recovery", "E", "Water Supply, Sewerage, Waste Management and Remediation"),
        ("38.31", "Incineration without energy recovery", "E", "Water Supply, Sewerage, Waste Management and Remediation"),
        ("38.32", "Landfilling or permanent storage", "E", "Water Supply, Sewerage, Waste Management and Remediation"),
        ("38.33", "Other waste disposal", "E", "Water Supply, Sewerage, Waste Management and Remediation"),
        ("39.00", "Remediation activities and other waste management service activities", "E", "Water Supply, Sewerage, Waste Management and Remediation"),
        ("41.00", "Construction of residential and non-residential buildings", "F", "Construction"),
        ("42.11", "Construction of roads and motorways", "F", "Construction"),
        ("42.12", "Construction of railways and underground railways", "F", "Construction"),
        ("42.13", "Construction of bridges and tunnels", "F", "Construction"),
        ("42.21", "Construction of utility projects for fluids", "F", "Construction"),
        ("42.22", "Construction of utility projects for electricity and telecommunications", "F", "Construction"),
        ("42.91", "Construction of water projects", "F", "Construction"),
        ("42.99", "Construction of other civil engineering projects n.e.c.", "F", "Construction"),
        ("43.11", "Demolition", "F", "Construction"),
        ("43.12", "Site preparation", "F", "Construction"),
        ("43.13", "Test drilling and boring", "F", "Construction"),
        ("43.21", "Electrical installation", "F", "Construction"),
        ("43.22", "Plumbing, heat and air-conditioning installation", "F", "Construction"),
        ("43.23", "Installation of insulation", "F", "Construction"),
        ("43.24", "Other construction installation", "F", "Construction"),
        ("43.31", "Plastering", "F", "Construction"),
        ("43.32", "Joinery installation", "F", "Construction"),
        ("43.33", "Floor and wall covering", "F", "Construction"),
        ("43.34", "Painting and glazing", "F", "Construction"),
        ("43.35", "Other building completion and finishing", "F", "Construction"),
        ("43.41", "Roofing activities", "F", "Construction"),
        ("43.42", "Other specialised construction activities in construction of buildings", "F", "Construction"),
        ("43.50", "Specialised construction activities in civil engineering", "F", "Construction"),
        ("43.60", "Intermediation service activities for specialised construction services", "F", "Construction"),
        ("43.91", "Masonry and bricklaying activities", "F", "Construction"),
        ("43.99", "Other specialised construction activities n.e.c.", "F", "Construction"),
        ("46.11", "Activities of agents involved in the wholesale of agricultural raw materials, live animals, textile", "G", "Wholesale and Retail Trade"),
        ("46.12", "Activities of agents involved in the wholesale of fuels, ores, metals and industrial chemicals", "G", "Wholesale and Retail Trade"),
        ("46.13", "Activities of agents involved in the wholesale of timber and building materials", "G", "Wholesale and Retail Trade"),
        ("46.14", "Activities of agents involved in the wholesale of machinery, industrial equipment, ships and", "G", "Wholesale and Retail Trade"),
        ("46.15", "Activities of agents involved in the wholesale of furniture, household goods, hardware and", "G", "Wholesale and Retail Trade"),
        ("46.16", "Activities of agents involved in the wholesale of textiles, clothing, fur, footwear and leather", "G", "Wholesale and Retail Trade"),
        ("46.17", "Activities of agents involved in the wholesale of food, beverages and tobacco", "G", "Wholesale and Retail Trade"),
        ("46.18", "Activities of agents involved in the wholesale of other particular products", "G", "Wholesale and Retail Trade"),
        ("46.19", "Activities of agents involved in non-specialised wholesale", "G", "Wholesale and Retail Trade"),
        ("46.21", "Wholesale of grain, unmanufactured tobacco, seeds and animal feeds", "G", "Wholesale and Retail Trade"),
        ("46.22", "Wholesale of flowers and plants", "G", "Wholesale and Retail Trade"),
        ("46.23", "Wholesale of live animals", "G", "Wholesale and Retail Trade"),
        ("46.24", "Wholesale of hides, skins and leather", "G", "Wholesale and Retail Trade"),
        ("46.31", "Wholesale of fruit and vegetables", "G", "Wholesale and Retail Trade"),
        ("46.32", "Wholesale of meat, meat products, fish and fish products", "G", "Wholesale and Retail Trade"),
        ("46.33", "Wholesale of dairy products, eggs and edible oils and fats", "G", "Wholesale and Retail Trade"),
        ("46.34", "Wholesale of beverages", "G", "Wholesale and Retail Trade"),
        ("46.35", "Wholesale of tobacco products", "G", "Wholesale and Retail Trade"),
        ("46.36", "Wholesale of sugar, chocolate and sugar confectionery", "G", "Wholesale and Retail Trade"),
        ("46.37", "Wholesale of coffee, tea, cocoa and spices", "G", "Wholesale and Retail Trade"),
        ("46.38", "Wholesale of other food", "G", "Wholesale and Retail Trade"),
        ("46.39", "Non-specialised wholesale of food, beverages and tobacco", "G", "Wholesale and Retail Trade"),
        ("46.41", "Wholesale of textiles", "G", "Wholesale and Retail Trade"),
        ("46.42", "Wholesale of clothing and footwear", "G", "Wholesale and Retail Trade"),
        ("46.43", "Wholesale of electrical household appliances", "G", "Wholesale and Retail Trade"),
        ("46.44", "Wholesale of china and glassware and cleaning materials", "G", "Wholesale and Retail Trade"),
        ("46.45", "Wholesale of perfume and cosmetics", "G", "Wholesale and Retail Trade"),
        ("46.46", "Wholesale of pharmaceutical and medical goods", "G", "Wholesale and Retail Trade"),
        ("46.47", "Wholesale of household, office and shop furniture, carpets and lighting equipment", "G", "Wholesale and Retail Trade"),
        ("46.48", "Wholesale of watches and jewellery", "G", "Wholesale and Retail Trade"),
        ("46.49", "Wholesale of other household goods", "G", "Wholesale and Retail Trade"),
        ("46.50", "Wholesale of information and communication equipment", "G", "Wholesale and Retail Trade"),
        ("46.61", "Wholesale of agricultural machinery, equipment and supplies", "G", "Wholesale and Retail Trade"),
        ("46.62", "Wholesale of machine tools", "G", "Wholesale and Retail Trade"),
        ("46.63", "Wholesale of mining, construction and civil engineering machinery", "G", "Wholesale and Retail Trade"),
        ("46.64", "Wholesale of other machinery and equipment", "G", "Wholesale and Retail Trade"),
        ("46.71", "Wholesale of motor vehicles", "G", "Wholesale and Retail Trade"),
        ("46.72", "Wholesale of motor vehicle parts and accessories", "G", "Wholesale and Retail Trade"),
        ("46.73", "Wholesale of motorcycles, motorcycle parts and accessories", "G", "Wholesale and Retail Trade"),
        ("46.81", "Wholesale of solid, liquid and gaseous fuels and related products", "G", "Wholesale and Retail Trade"),
        ("46.82", "Wholesale of metals and metal ores", "G", "Wholesale and Retail Trade"),
        ("46.83", "Wholesale of wood, construction materials and sanitary equipment", "G", "Wholesale and Retail Trade"),
        ("46.84", "Wholesale of hardware, plumbing and heating equipment and supplies", "G", "Wholesale and Retail Trade"),
        ("46.85", "Wholesale of chemical products", "G", "Wholesale and Retail Trade"),
        ("46.86", "Wholesale of other intermediate products", "G", "Wholesale and Retail Trade"),
        ("46.87", "Wholesale of waste and scrap", "G", "Wholesale and Retail Trade"),
        ("46.89", "Other specialised wholesale n.e.c.", "G", "Wholesale and Retail Trade"),
        ("46.90", "Non-specialised wholesale trade", "G", "Wholesale and Retail Trade"),
        ("47.11", "Non-specialised retail sale of predominately food, beverages or tobacco", "G", "Wholesale and Retail Trade"),
        ("47.12", "Other non-specialised retail sale", "G", "Wholesale and Retail Trade"),
        ("47.21", "Retail sale of fruit and vegetables", "G", "Wholesale and Retail Trade"),
        ("47.22", "Retail sale of meat and meat products", "G", "Wholesale and Retail Trade"),
        ("47.23", "Retail sale of fish, crustaceans and molluscs", "G", "Wholesale and Retail Trade"),
        ("47.24", "Retail sale of bread, cake and confectionery", "G", "Wholesale and Retail Trade"),
        ("47.25", "Retail sale of beverages", "G", "Wholesale and Retail Trade"),
        ("47.26", "Retail sale of tobacco products", "G", "Wholesale and Retail Trade"),
        ("47.27", "Retail sale of other food", "G", "Wholesale and Retail Trade"),
        ("47.30", "Retail sale of automotive fuel", "G", "Wholesale and Retail Trade"),
        ("47.40", "Retail sale of information and communication equipment", "G", "Wholesale and Retail Trade"),
        ("47.51", "Retail sale of textiles", "G", "Wholesale and Retail Trade"),
        ("47.52", "Retail sale of hardware, building materials, paints and glass", "G", "Wholesale and Retail Trade"),
        ("47.53", "Retail sale of carpets, rugs, wall and floor coverings", "G", "Wholesale and Retail Trade"),
        ("47.54", "Retail sale of electrical household appliances", "G", "Wholesale and Retail Trade"),
        ("47.55", "Retail sale of furniture, lighting equipment, tableware and other household goods", "G", "Wholesale and Retail Trade"),
        ("47.61", "Retail sale of books", "G", "Wholesale and Retail Trade"),
        ("47.62", "Retail sale of newspapers, and other periodical publications and stationery", "G", "Wholesale and Retail Trade"),
        ("47.63", "Retail sale of sporting equipment", "G", "Wholesale and Retail Trade"),
        ("47.64", "Retail sale of games and toys", "G", "Wholesale and Retail Trade"),
        ("47.69", "Retail sale of cultural and recreational goods n.e.c.", "G", "Wholesale and Retail Trade"),
        ("47.71", "Retail sale of clothing", "G", "Wholesale and Retail Trade"),
        ("47.72", "Retail sale of footwear and leather goods", "G", "Wholesale and Retail Trade"),
        ("47.73", "Retail sale of pharmaceutical products", "G", "Wholesale and Retail Trade"),
        ("47.74", "Retail sale of medical and orthopaedic goods", "G", "Wholesale and Retail Trade"),
        ("47.75", "Retail sale of cosmetic and toilet articles", "G", "Wholesale and Retail Trade"),
        ("47.76", "Retail sale of flowers, plants, fertilisers, pets and pet food", "G", "Wholesale and Retail Trade"),
        ("47.77", "Retail sale of watches and jewellery", "G", "Wholesale and Retail Trade"),
        ("47.78", "Retail sale of other new goods", "G", "Wholesale and Retail Trade"),
        ("47.79", "Retail sale of second-hand goods", "G", "Wholesale and Retail Trade"),
        ("47.81", "Retail sale of motor vehicles", "G", "Wholesale and Retail Trade"),
        ("47.82", "Retail sale of motor vehicle parts and accessories", "G", "Wholesale and Retail Trade"),
        ("47.83", "Retail sale of motorcycles, motorcycle parts and accessories", "G", "Wholesale and Retail Trade"),
        ("47.91", "Intermediation service activities for non-specialised retail sale", "G", "Wholesale and Retail Trade"),
        ("47.92", "Intermediation service activities for specialised retail sale", "G", "Wholesale and Retail Trade"),
        ("49.11", "Passenger heavy rail transport", "H", "Transportation and Storage"),
        ("49.12", "Other passenger rail transport", "H", "Transportation and Storage"),
        ("49.20", "Freight rail transport", "H", "Transportation and Storage"),
        ("49.31", "Scheduled passenger transport by road", "H", "Transportation and Storage"),
        ("49.32", "Non-scheduled passenger transport by road", "H", "Transportation and Storage"),
        ("49.33", "On-demand passenger transport service activities by vehicle with driver", "H", "Transportation and Storage"),
        ("49.34", "Passenger transport by cableways and ski lifts", "H", "Transportation and Storage"),
        ("49.39", "Other passenger land transport n.e.c.", "H", "Transportation and Storage"),
        ("49.41", "Freight transport by road", "H", "Transportation and Storage"),
        ("49.42", "Removal services", "H", "Transportation and Storage"),
        ("49.50", "Transport via pipeline", "H", "Transportation and Storage"),
        ("50.10", "Sea and coastal passenger water transport", "H", "Transportation and Storage"),
        ("50.20", "Sea and coastal freight water transport", "H", "Transportation and Storage"),
        ("50.30", "Inland passenger water transport", "H", "Transportation and Storage"),
        ("50.40", "Inland freight water transport", "H", "Transportation and Storage"),
        ("51.10", "Passenger air transport", "H", "Transportation and Storage"),
        ("51.21", "Freight air transport", "H", "Transportation and Storage"),
        ("51.22", "Space transport", "H", "Transportation and Storage"),
        ("52.10", "Warehousing and storage", "H", "Transportation and Storage"),
        ("52.21", "Service activities incidental to land transportation", "H", "Transportation and Storage"),
        ("52.22", "Service activities incidental to water transportation", "H", "Transportation and Storage"),
        ("52.23", "Service activities incidental to air transportation", "H", "Transportation and Storage"),
        ("52.24", "Cargo handling", "H", "Transportation and Storage"),
        ("52.25", "Logistics service activities", "H", "Transportation and Storage"),
        ("52.26", "Other support activities for transportation", "H", "Transportation and Storage"),
        ("52.31", "Intermediation service activities for freight transportation", "H", "Transportation and Storage"),
        ("52.32", "Intermediation service activities for passenger transportation", "H", "Transportation and Storage"),
        ("53.10", "Postal activities under universal service obligation", "H", "Transportation and Storage"),
        ("53.20", "Other postal and courier activities", "H", "Transportation and Storage"),
        ("53.30", "Intermediation service activities for postal and courier activities", "H", "Transportation and Storage"),
        ("55.10", "Hotels and similar accommodation", "I", "Accommodation and Food Service Activities"),
        ("55.20", "Holiday and other short-stay accommodation", "I", "Accommodation and Food Service Activities"),
        ("55.30", "Camping grounds and recreational vehicle parks", "I", "Accommodation and Food Service Activities"),
        ("55.40", "Intermediation service activities for accommodation", "I", "Accommodation and Food Service Activities"),
        ("55.90", "Other accommodation", "I", "Accommodation and Food Service Activities"),
        ("56.11", "Restaurant activities", "I", "Accommodation and Food Service Activities"),
        ("56.12", "Mobile food service activities", "I", "Accommodation and Food Service Activities"),
        ("56.21", "Event catering activities", "I", "Accommodation and Food Service Activities"),
        ("56.22", "Contract catering service activities and other food service activities", "I", "Accommodation and Food Service Activities"),
        ("56.30", "Beverage serving activities", "I", "Accommodation and Food Service Activities"),
        ("56.40", "Intermediation service activities for food and beverage services activities", "I", "Accommodation and Food Service Activities"),
        ("58.11", "Publishing of books", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("58.12", "Publishing of newspapers", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("58.13", "Publishing of journals and periodicals", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("58.19", "Other publishing activities, except software publishing", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("58.21", "Publishing of video games", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("58.29", "Other software publishing", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("59.11", "Motion picture, video and television programme production activities", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("59.12", "Motion picture, video and television programme post-production activities", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("59.13", "Motion picture and video distribution activities", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("59.14", "Motion picture projection activities", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("59.20", "Sound recording and music publishing activities", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("60.10", "Radio broadcasting and audio distribution activities", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("60.20", "Television programming, broadcasting and video distribution activities", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("60.31", "News agency activities", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("60.39", "Other content distribution activities", "J", "Publishing, Broadcasting and Content Production and Distribution"),
        ("61.10", "Wired, wireless, and satellite telecommunication activities", "K", "Telecommunication, Computer Programming, Consulting and Computing Infrastructure"),
        ("61.20", "Telecommunication reselling activities and intermediation service activities for", "K", "Telecommunication, Computer Programming, Consulting and Computing Infrastructure"),
        ("61.90", "Other telecommunication activities", "K", "Telecommunication, Computer Programming, Consulting and Computing Infrastructure"),
        ("62.10", "Computer programming activities", "K", "Telecommunication, Computer Programming, Consulting and Computing Infrastructure"),
        ("62.20", "Computer consultancy and computer facilities management activities", "K", "Telecommunication, Computer Programming, Consulting and Computing Infrastructure"),
        ("62.90", "Other information technology and computer service activities", "K", "Telecommunication, Computer Programming, Consulting and Computing Infrastructure"),
        ("63.10", "Computing infrastructure, data processing, hosting and related activities", "K", "Telecommunication, Computer Programming, Consulting and Computing Infrastructure"),
        ("63.91", "Web search portal activities", "K", "Telecommunication, Computer Programming, Consulting and Computing Infrastructure"),
        ("63.92", "Other information service activities", "K", "Telecommunication, Computer Programming, Consulting and Computing Infrastructure"),
        ("64.11", "Central banking", "L", "Financial and Insurance Activities"),
        ("64.19", "Other monetary intermediation", "L", "Financial and Insurance Activities"),
        ("64.21", "Activities of holding companies", "L", "Financial and Insurance Activities"),
        ("64.22", "Activities of financing conduits", "L", "Financial and Insurance Activities"),
        ("64.31", "Activities of money market and non-money market investments funds", "L", "Financial and Insurance Activities"),
        ("64.32", "Activities of trust, estate and agency accounts", "L", "Financial and Insurance Activities"),
        ("64.91", "Financial leasing", "L", "Financial and Insurance Activities"),
        ("64.92", "Other credit granting", "L", "Financial and Insurance Activities"),
        ("64.99", "Other financial service activities, except insurance and pension funding n.e.c.", "L", "Financial and Insurance Activities"),
        ("65.11", "Life insurance", "L", "Financial and Insurance Activities"),
        ("65.12", "Non-life insurance", "L", "Financial and Insurance Activities"),
        ("65.20", "Reinsurance", "L", "Financial and Insurance Activities"),
        ("65.30", "Pension funding", "L", "Financial and Insurance Activities"),
        ("66.11", "Administration of financial markets", "L", "Financial and Insurance Activities"),
        ("66.12", "Security and commodity contracts brokerage", "L", "Financial and Insurance Activities"),
        ("66.19", "Other activities auxiliary to financial services, except insurance and pension funding", "L", "Financial and Insurance Activities"),
        ("66.21", "Risk and damage evaluation", "L", "Financial and Insurance Activities"),
        ("66.22", "Activities of insurance agents and brokers", "L", "Financial and Insurance Activities"),
        ("66.29", "Activities auxiliary to insurance and pension funding n.e.c.", "L", "Financial and Insurance Activities"),
        ("66.30", "Fund management activities", "L", "Financial and Insurance Activities"),
        ("68.11", "Buying and selling of own real estate", "M", "Real Estate Activities"),
        ("68.12", "Development of building projects", "M", "Real Estate Activities"),
        ("68.20", "Rental and operating of own or leased real estate", "M", "Real Estate Activities"),
        ("68.31", "Intermediation service activities for real estate activities", "M", "Real Estate Activities"),
        ("68.32", "Other real estate activities on a fee or contract basis", "M", "Real Estate Activities"),
        ("69.10", "Legal activities", "N", "Professional, Scientific and Technical Activities"),
        ("69.20", "Accounting, bookkeeping and auditing activities; tax consultancy", "N", "Professional, Scientific and Technical Activities"),
        ("70.10", "Activities of head offices", "N", "Professional, Scientific and Technical Activities"),
        ("70.20", "Business and other management consultancy activities", "N", "Professional, Scientific and Technical Activities"),
        ("71.11", "Architectural activities", "N", "Professional, Scientific and Technical Activities"),
        ("71.12", "Engineering activities and related technical consultancy", "N", "Professional, Scientific and Technical Activities"),
        ("71.20", "Technical testing and analysis", "N", "Professional, Scientific and Technical Activities"),
        ("72.10", "Research and experimental development on natural sciences and engineering", "N", "Professional, Scientific and Technical Activities"),
        ("72.20", "Research and experimental development on social sciences and humanities", "N", "Professional, Scientific and Technical Activities"),
        ("73.11", "Activities of advertising agencies", "N", "Professional, Scientific and Technical Activities"),
        ("73.12", "Media representation", "N", "Professional, Scientific and Technical Activities"),
        ("73.20", "Market research and public opinion polling", "N", "Professional, Scientific and Technical Activities"),
        ("73.30", "Public relations and communication activities", "N", "Professional, Scientific and Technical Activities"),
        ("74.11", "Industrial product and fashion design activities", "N", "Professional, Scientific and Technical Activities"),
        ("74.12", "Graphic design and visual communication activities", "N", "Professional, Scientific and Technical Activities"),
        ("74.13", "Interior design activities", "N", "Professional, Scientific and Technical Activities"),
        ("74.14", "Other specialised design activities", "N", "Professional, Scientific and Technical Activities"),
        ("74.20", "Photographic activities", "N", "Professional, Scientific and Technical Activities"),
        ("74.30", "Translation and interpretation activities", "N", "Professional, Scientific and Technical Activities"),
        ("74.91", "Patent brokering and marketing service activities", "N", "Professional, Scientific and Technical Activities"),
        ("74.99", "All other professional, scientific and technical activities n.e.c.", "N", "Professional, Scientific and Technical Activities"),
        ("75.00", "Veterinary activities", "N", "Professional, Scientific and Technical Activities"),
        ("77.11", "Rental and leasing of cars and light motor vehicles", "O", "Administrative and Support Service Activities"),
        ("77.12", "Rental and leasing of trucks", "O", "Administrative and Support Service Activities"),
        ("77.21", "Rental and leasing of recreational and sports goods", "O", "Administrative and Support Service Activities"),
        ("77.22", "Rental and leasing of other personal and household goods", "O", "Administrative and Support Service Activities"),
        ("77.31", "Rental and leasing of agricultural machinery and equipment", "O", "Administrative and Support Service Activities"),
        ("77.32", "Rental and leasing of construction and civil engineering machinery and equipment", "O", "Administrative and Support Service Activities"),
        ("77.33", "Rental and leasing of office machinery, equipment and computers", "O", "Administrative and Support Service Activities"),
        ("77.34", "Rental and leasing of water transport equipment", "O", "Administrative and Support Service Activities"),
        ("77.35", "Rental and leasing of air transport equipment", "O", "Administrative and Support Service Activities"),
        ("77.39", "Rental and leasing of other machinery, equipment and tangible goods n.e.c.", "O", "Administrative and Support Service Activities"),
        ("77.40", "Leasing of intellectual property and similar products, except copyrighted works", "O", "Administrative and Support Service Activities"),
        ("77.51", "Intermediation service activities for rental and leasing of cars, motorhomes and trailers", "O", "Administrative and Support Service Activities"),
        ("77.52", "Intermediation service activities for rental and leasing of other tangible goods and non-", "O", "Administrative and Support Service Activities"),
        ("78.10", "Activities of employment placement agencies", "O", "Administrative and Support Service Activities"),
        ("78.20", "Temporary employment agency activities and other human resource provisions", "O", "Administrative and Support Service Activities"),
        ("79.11", "Travel agency activities", "O", "Administrative and Support Service Activities"),
        ("79.12", "Tour operator activities", "O", "Administrative and Support Service Activities"),
        ("79.90", "Other reservation service and related activities", "O", "Administrative and Support Service Activities"),
        ("80.01", "Investigation and private security activities", "O", "Administrative and Support Service Activities"),
        ("80.09", "Security activities n.e.c.", "O", "Administrative and Support Service Activities"),
        ("81.10", "Combined facilities support activities", "O", "Administrative and Support Service Activities"),
        ("81.21", "General cleaning of buildings", "O", "Administrative and Support Service Activities"),
        ("81.22", "Other building and industrial cleaning activities", "O", "Administrative and Support Service Activities"),
        ("81.23", "Other cleaning activities", "O", "Administrative and Support Service Activities"),
        ("81.30", "Landscape service activities", "O", "Administrative and Support Service Activities"),
        ("82.10", "Office administrative and support activities", "O", "Administrative and Support Service Activities"),
        ("82.20", "Activities of call centres", "O", "Administrative and Support Service Activities"),
        ("82.30", "Organisation of conventions and trade shows", "O", "Administrative and Support Service Activities"),
        ("82.40", "Intermediation service activities for business support service activities n.e.c.", "O", "Administrative and Support Service Activities"),
        ("82.91", "Activities of collection agencies and credit bureaus", "O", "Administrative and Support Service Activities"),
        ("82.92", "Packaging activities", "O", "Administrative and Support Service Activities"),
        ("82.99", "Other business support service activities n.e.c.", "O", "Administrative and Support Service Activities"),
        ("84.11", "General public administration activities", "P", "Public Administration and Defence; Compulsory Social Security"),
        ("84.12", "Regulation of health care, education, cultural services and other social services", "P", "Public Administration and Defence; Compulsory Social Security"),
        ("84.13", "Regulation of and contribution to more efficient operation of businesses", "P", "Public Administration and Defence; Compulsory Social Security"),
        ("84.21", "Foreign affairs", "P", "Public Administration and Defence; Compulsory Social Security"),
        ("84.22", "Defence activities", "P", "Public Administration and Defence; Compulsory Social Security"),
        ("84.23", "Justice and judicial activities", "P", "Public Administration and Defence; Compulsory Social Security"),
        ("84.24", "Public order and safety activities", "P", "Public Administration and Defence; Compulsory Social Security"),
        ("84.25", "Fire service activities", "P", "Public Administration and Defence; Compulsory Social Security"),
        ("84.30", "Compulsory social security activities", "P", "Public Administration and Defence; Compulsory Social Security"),
        ("85.10", "Pre-primary education", "Q", "Education"),
        ("85.20", "Primary education", "Q", "Education"),
        ("85.31", "General secondary education", "Q", "Education"),
        ("85.32", "Vocational secondary education", "Q", "Education"),
        ("85.33", "Post-secondary non-tertiary education", "Q", "Education"),
        ("85.40", "Tertiary education", "Q", "Education"),
        ("85.51", "Sports and recreation education", "Q", "Education"),
        ("85.52", "Cultural education", "Q", "Education"),
        ("85.53", "Driving school activities", "Q", "Education"),
        ("85.59", "Other education n.e.c.", "Q", "Education"),
        ("85.61", "Intermediation service activities for courses and tutors", "Q", "Education"),
        ("85.69", "Educational support activities n.e.c.", "Q", "Education"),
        ("86.10", "Hospital activities", "R", "Human Health and Social Work Activities"),
        ("86.21", "General medical practice activities", "R", "Human Health and Social Work Activities"),
        ("86.22", "Medical specialists activities", "R", "Human Health and Social Work Activities"),
        ("86.23", "Dental practice care activities", "R", "Human Health and Social Work Activities"),
        ("86.91", "Diagnostic imaging services and medical laboratory activities", "R", "Human Health and Social Work Activities"),
        ("86.92", "Patient transportation by ambulance", "R", "Human Health and Social Work Activities"),
        ("86.93", "Activities of psychologists and psychotherapists, except medical doctors", "R", "Human Health and Social Work Activities"),
        ("86.94", "Nursing and midwifery activities", "R", "Human Health and Social Work Activities"),
        ("86.95", "Physiotherapy activities", "R", "Human Health and Social Work Activities"),
        ("86.96", "Traditional, complementary and alternative medicine activities", "R", "Human Health and Social Work Activities"),
        ("86.97", "Intermediation service activities for medical, dental and other human health services", "R", "Human Health and Social Work Activities"),
        ("86.99", "Other human health activities n.e.c.", "R", "Human Health and Social Work Activities"),
        ("87.10", "Residential nursing care activities", "R", "Human Health and Social Work Activities"),
        ("87.20", "Residential care activities for persons living with or having a diagnosis of a mental illness or", "R", "Human Health and Social Work Activities"),
        ("87.30", "Residential care activities for older persons or persons with physical disabilities", "R", "Human Health and Social Work Activities"),
        ("87.91", "Intermediation service activities for residential care activities", "R", "Human Health and Social Work Activities"),
        ("87.99", "Other residential care activities n.e.c.", "R", "Human Health and Social Work Activities"),
        ("88.10", "Social work activities without accommodation for older persons or persons with disabilities", "R", "Human Health and Social Work Activities"),
        ("88.91", "Child day-care activities", "R", "Human Health and Social Work Activities"),
        ("88.99", "Other social work activities without accommodation n.e.c.", "R", "Human Health and Social Work Activities"),
        ("90.11", "Literary creation and musical composition activities", "S", "Arts, Sports and Recreation"),
        ("90.12", "Visual arts creation activities", "S", "Arts, Sports and Recreation"),
        ("90.13", "Other arts creation activities", "S", "Arts, Sports and Recreation"),
        ("90.20", "Activities of performing arts", "S", "Arts, Sports and Recreation"),
        ("90.31", "Operation of arts facilities and sites", "S", "Arts, Sports and Recreation"),
        ("90.39", "Other support activities to arts and performing arts", "S", "Arts, Sports and Recreation"),
        ("91.11", "Library activities", "S", "Arts, Sports and Recreation"),
        ("91.12", "Archive activities", "S", "Arts, Sports and Recreation"),
        ("91.21", "Museum and collection activities", "S", "Arts, Sports and Recreation"),
        ("91.22", "Historical site and monument activities", "S", "Arts, Sports and Recreation"),
        ("91.30", "Conservation, restoration and other support activities for cultural heritage", "S", "Arts, Sports and Recreation"),
        ("91.41", "Botanical and zoological garden activities", "S", "Arts, Sports and Recreation"),
        ("91.42", "Nature reserve activities", "S", "Arts, Sports and Recreation"),
        ("92.00", "Gambling and betting activities", "S", "Arts, Sports and Recreation"),
        ("93.11", "Operation of sports facilities", "S", "Arts, Sports and Recreation"),
        ("93.12", "Activities of sports clubs", "S", "Arts, Sports and Recreation"),
        ("93.13", "Activities of fitness centres", "S", "Arts, Sports and Recreation"),
        ("93.19", "Sports activities n.e.c.", "S", "Arts, Sports and Recreation"),
        ("93.21", "Activities of amusement parks and theme parks", "S", "Arts, Sports and Recreation"),
        ("93.29", "Amusement and recreation activities n.e.c.", "S", "Arts, Sports and Recreation"),
        ("94.11", "Activities of business and employers membership organisations", "T", "Other Service Activities"),
        ("94.12", "Activities of professional membership organisations", "T", "Other Service Activities"),
        ("94.20", "Activities of trade unions", "T", "Other Service Activities"),
        ("94.91", "Activities of religious organisations", "T", "Other Service Activities"),
        ("94.92", "Activities of political organisations", "T", "Other Service Activities"),
        ("94.99", "Activities of other membership organisations n.e.c.", "T", "Other Service Activities"),
        ("95.10", "Repair and maintenance of computers and communication equipment", "T", "Other Service Activities"),
        ("95.21", "Repair and maintenance of consumer electronics", "T", "Other Service Activities"),
        ("95.22", "Repair and maintenance of household appliances and home and garden equipment", "T", "Other Service Activities"),
        ("95.23", "Repair and maintenance of footwear and leather goods", "T", "Other Service Activities"),
        ("95.24", "Repair and maintenance of furniture and home furnishings", "T", "Other Service Activities"),
        ("95.25", "Repair and maintenance of watches, clocks and jewellery", "T", "Other Service Activities"),
        ("95.29", "Repair and maintenance of personal and household goods n.e.c.", "T", "Other Service Activities"),
        ("95.31", "Repair and maintenance of motor vehicles", "T", "Other Service Activities"),
        ("95.32", "Repair and maintenance of motorcycles", "T", "Other Service Activities"),
        ("95.40", "Intermediation service activities for repair and maintenance of computers, personal and", "T", "Other Service Activities"),
        ("96.10", "Washing and cleaning of textile and fur products", "T", "Other Service Activities"),
        ("96.21", "Hairdressing and barber activities", "T", "Other Service Activities"),
        ("96.22", "Beauty care and other beauty treatment activities", "T", "Other Service Activities"),
        ("96.23", "Day spa, sauna and steam bath activities", "T", "Other Service Activities"),
        ("96.30", "Funeral and related activities", "T", "Other Service Activities"),
        ("96.40", "Intermediation service activities for personal services", "T", "Other Service Activities"),
        ("96.91", "Provision of domestic personal service activities", "T", "Other Service Activities"),
        ("96.99", "Other personal service activities n.e.c.", "T", "Other Service Activities"),
        ("97.00", "Activities of households as employers of domestic personnel", "U", "Activities of Households as Employers"),
        ("98.10", "Undifferentiated goods-producing activities of private households for own use", "U", "Activities of Households as Employers"),
        ("98.20", "Undifferentiated service-producing activities of private households for own use", "U", "Activities of Households as Employers"),
        ("99.00", "Activities of extraterritorial organisations and bodies", "V", "Activities of Extraterritorial Organisations and Bodies"),
    ];
}
